# Generated by the environmentConfig plugin; StaticClassConfigFieldProvider loads it
# with Class.forName and newInstance, so the constructor must survive too.
# Core's own keep does not reach Pass.
-keep class me.proton.core.configuration.EnvironmentConfigurationDefaults {
    <init>();
    public static <fields>;
}

# Read at runtime via Class.getAnnotation/annotations (SetupProductMetrics, ObservabilityData).
# Instances are runtime proxies, so R8 full mode sees no implementations and
# would otherwise fold every value of these types to null.
-keep @interface me.proton.core.telemetry.presentation.annotation.** { *; }
-keep @interface me.proton.core.observability.domain.entity.SchemaId { *; }

# Mirrors proton-libs proguard-rules/core-libs.pro, which is not on Pass's classpath.
-keeppackagenames me.proton.core.**

# Parcelables can outlive an app update inside PendingIntent extras.
-keepnames class me.proton.core.** implements android.os.Parcelable

# Stage A: allow shrinking and optimisation over core, but pin names until the
# mapping is also uploaded to the Account Sentry project (ACCOUNT_SENTRY_DSN).
-keep,allowshrinking,allowoptimization,allowaccessmodification class me.proton.core.** { *; }
