# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Assemble the DevBlackDebug apk"
  lane :assembleDevBlackDebug do
    gradle(task: ":app:assembleDevBlackDebug")
  end

  desc "Assemble the DevBlackRelease apk"
  lane :assembleDevBlackRelease do
    gradle(task: ":app:assembleDevBlackRelease -PapkBuild=true")
  end

  desc "Assemble the AlphaProdDebug apk"
  lane :assembleAlphaProdDebug do
    gradle(task: ":app:assembleAlphaProdDebug")
  end

  desc "Assemble the AlphaProdRelease apk"
  lane :assembleAlphaProdRelease do
    gradle(task: ":app:assembleAlphaProdRelease -PapkBuild=true")
  end

  desc "Assemble the PlayProdDebug apk"
  lane :assemblePlayProdDebug do
    gradle(task: ":app:assemblePlayProdDebug")
  end

  desc "Assemble the PlayBlackRelease apk"
  lane :assemblePlayBlackRelease do
    gradle(task: ":app:assemblePlayBlackRelease -PapkBuild=true")
  end

  desc "Creates the PlayProdRelease bundle"
  lane :buildPlayProdReleaseBundle do
    gradle(task: ":app:bundlePlayProdRelease")
  end

  desc "Creates the PlayProdRelease apk"
  lane :buildPlayProdReleaseApk do
    gradle(task: ":app:assemblePlayProdRelease -PapkBuild=true")
  end

  desc "Assemble the DevDebug E2E apk"
  lane :assembleE2EDevDebug do
    gradle(task: ":pass:autofill:e2e-app:assembleDevDebug")
  end

  desc "Assemble the androidTest apks"
  lane :assembleDebugAndroidTest do
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Assemble DevBlackDebug and AndroidTest apks"
  lane :assembleDevBlackDebugWithAndroidTests do
    gradle(tasks: [":app:assembleDevBlackDebug", "assembleDebugAndroidTest", "assembleDevDebugAndroidTest"])
  end

  desc "Run Unit tests"
  lane :unitTests do
    gradle(task: "testDebugUnitTest")
    gradle(task: "testDevDebugUnitTest -x :pass:screenshot-tests:testDevDebugUnitTest")
  end

  desc "Verify screenshot tests"
  lane :verifyScreenshotTests do
    gradle(task: "verifyPaparazziDevDebug")
  end

  desc "Run instrumentation tests"
  lane :instrumentationTests do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/setupGoogleCloud.sh")
    gradle(task: "runFlank")
  end

  desc "Publish dev build to firebase group"
  lane :deployToFirebaseDevGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh devBlack")
  end

  desc "Publish alpha build to firebase group"
  lane :deployToFirebaseAlphaGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh alphaProd")
  end

  desc "Publish prod black build to firebase group"
  lane :deployToFirebaseProdGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh playBlack")
  end

  desc "Publish internal prod bundle"
  lane :deployToPlayInternal do
     upload_to_play_store(
       json_key: './tmp/play-service-account.json',
       track: 'internal',
       release_status: 'draft',
       aab: './app/build/outputs/bundle/playProdRelease/app-play-prod-release.aab',
       skip_upload_metadata: true,
       skip_upload_changelogs: true,
       skip_upload_images: true,
       skip_upload_screenshots: true,
       sync_image_upload: true
     )
     sh("../tools/private/publish/slack-publish.sh")
  end
end
