# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Run code analysis"
  lane :analyse do
    gradle(task: "multiModuleDetekt")
  end

  desc "Assemble the devDebug apk"
  lane :assembleDevDebug do
    gradle(task: ":app:assembleDevDebug")
  end

  desc "Assemble the alphaDebug apk"
  lane :assembleAlphaDebug do
    gradle(task: ":app:assembleAlphaDebug")
  end

  desc "Assemble the prodDebug apk"
  lane :assembleProdDebug do
    gradle(task: ":app:assembleProdDebug")
  end

  desc "Assemble the devRelease apk"
  lane :assembleDevRelease do
    gradle(task: ":app:assembleDevRelease")
  end

  desc "Assemble the alphaRelease apk"
  lane :assembleAlphaRelease do
    gradle(task: ":app:assembleAlphaRelease")
  end

  desc "Creates the prodRelease bundle"
  lane :bundleProdRelease do
    gradle(task: ":app:bundleProdRelease")
  end

  desc "Assemble the androidTest apks"
  lane :assembleDebugAndroidTest do
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Run Unit tests"
  lane :unitTests do
    gradle(task: "testDebugUnitTest")
    gradle(task: "testDevDebugUnitTest")
  end

  desc "Verify screenshot tests"
  lane :verifyScreenshotTests do
    gradle(task: "verifyPaparazziDevDebug")
  end

  desc "Run instrumentation tests"
  lane :instrumentationTests do
    sh("../scripts/ci/installFirebase.sh")
    sh("../scripts/ci/setupGoogleJson.sh")
    sh("../scripts/ci/setupGoogleCloud.sh")
    sh("../scripts/launchFirebaseInstrumentedTests.sh")
  end

  desc "Publish dev build to firebase group"
  lane :deployToFirebaseDevGroup do
    sh("../scripts/ci/installFirebase.sh")
    sh("../scripts/ci/setupGoogleJson.sh")
    sh("../scripts/uploadApkToFirebase.sh dev")
  end

  desc "Publish alpha build to firebase group"
  lane :deployToFirebaseAlphaGroup do
    sh("../scripts/ci/installFirebase.sh")
    sh("../scripts/ci/setupGoogleJson.sh")
    sh("../scripts/uploadApkToFirebase.sh alpha")
  end

  desc "Publish internal prod bundle"
  lane :deployToPlayInternal do
     upload_to_play_store(
       json_key: '../tmp/play-service-account.json',
       track: 'internal',
       release_status: 'draft',
       aab: '../app/build/outputs/bundle/prodRelease/app-prod-release.aab'
     )
  end
end
