# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Run instrumentation tests"
  lane :instrumentationTests do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/setupGoogleCloud.sh")
    gradle(task: "runFlank")
  end

  desc "Publish dev build to firebase group"
  lane :deployToFirebaseDevGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh devBlack")
  end

  desc "Publish alpha build to firebase group"
  lane :deployToFirebaseAlphaGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh alphaProd")
  end

  desc "Publish prod black build to firebase group"
  lane :deployToFirebaseProdGroup do
    sh("../tools/private/ci/installFirebase.sh")
    sh("../tools/private/ci/setupGoogleJson.sh")
    sh("../tools/private/ci/uploadApkToFirebase.sh playBlack")
  end

  desc "Publish internal prod bundle"
  lane :deployToPlayInternal do
     upload_to_play_store(
       json_key: './tmp/play-service-account.json',
       track: 'internal',
       release_status: 'draft',
       aab: './app/build/outputs/bundle/playProdRelease/app-play-prod-release.aab',
       skip_upload_metadata: true,
       skip_upload_changelogs: true,
       skip_upload_images: true,
       skip_upload_screenshots: true,
       sync_image_upload: true
     )
     sh("../tools/private/publish/slack-publish.sh")
  end
end
