#!/bin/bash

# Verifies the version metadata that F-Droid consumes from our GitHub tags.
# F-Droid's scanner (fdroidserver checkupdates.py) is told in fdroiddata's
# proton.android.pass.fdroid.yml to read exactly two things from this repo at
# each tag:
#   1. metadata/fdroid_version.txt - its UpdateCheckData regex extracts
#      versionCode/versionName from this fixed path, generated by
#      scripts/generateFdroidVersionFile.sh. If the versionCode there does not
#      exceed fdroiddata's CurrentVersionCode, F-Droid silently skips the release.
#   2. metadata/en-US/changelogs/<versionCode>.txt - one file per release, named
#      after the versionCode computed by scripts/versionCode.sh (e.g. 1.41.2 ->
#      14102000.txt). Missing file = broken changelog on the F-Droid listing.
# This script cross-checks both against .cz.yaml, appVersionName and the tag:
#   ./scripts/checkVersionConsistency.sh          # MR pipelines
#   ./scripts/checkVersionConsistency.sh 1.41.2   # tag pipelines / pre-release
# If the paths above ever move, update fdroiddata's .yml in the same change.

if [[ $# -gt 1 ]]; then
    echo "Invalid usage. ${0} [TAG]"
    exit 1
fi

set -uo pipefail

BUILD_GRADLE=app/build.gradle.kts

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

cz_version=$(awk -F': ' '/^  version:/ {print $2}' .cz.yaml)
gradle_version=$(sed -nE 's/^val appVersionName: String = "([^"]+)".*/\1/p' "$BUILD_GRADLE")
fdroid_name=$(sed -nE 's/^versionName=(.+)$/\1/p' metadata/fdroid_version.txt)
fdroid_code=$(sed -nE 's/^versionCode=([0-9]+)$/\1/p' metadata/fdroid_version.txt)
expected_code=$("$REPO_ROOT/scripts/versionCode.sh" "$fdroid_name")

fail=0
for value_name in "$cz_version:cz_version" "$gradle_version:gradle_version" "$fdroid_name:fdroid_version.txt versionName" "$fdroid_code:fdroid_version.txt versionCode" "$expected_code:computed versionCode"; do
    value="${value_name%%:*}"
    name="${value_name##*:}"
    if [[ -z "$value" ]]; then
        echo "ERROR: could not parse $name"
        fail=1
    fi
done

check() {
    if [[ "$1" == "$2" ]]; then
        echo "OK: $3 ($1)"
    else
        echo "ERROR: $3 mismatch: '$1' != '$2'"
        fail=1
    fi
}

check "$cz_version" "$gradle_version" ".cz.yaml vs appVersionName"
check "$fdroid_name" "$gradle_version" "fdroid_version.txt versionName vs appVersionName"
check "$fdroid_code" "$expected_code" "fdroid_version.txt versionCode vs computed from versionName"

if [[ -n "${1:-}" ]]; then
    check "$1" "$gradle_version" "git tag vs appVersionName"
    changelog="metadata/en-US/changelogs/$("$REPO_ROOT/scripts/versionCode.sh" "$1").txt"
    if [[ -f "$changelog" ]]; then
        echo "OK: changelog $changelog"
    else
        echo "ERROR: changelog $changelog not found"
        fail=1
    fi
fi

if [[ $fail -ne 0 ]]; then
    echo ""
    echo "Version metadata is inconsistent. If this is a release bump, re-run the commitizen"
    echo "bump so post_bump_hooks regenerate metadata/fdroid_version.txt"
    echo "(see scripts/generateFdroidVersionFile.sh)."
    exit 1
fi
